
# DEVELOPMENT ADDRESS
baseURL = "/"


# PRODUCTION ADDRESS
#baseURL = "https://globalgovernance.lab.mcgill.ca/"


# HUGO SETTINGS
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]
theme = "hugo-gg-lab-v2"


# SITE SETTINGS
title = "Global Governance Lab"
languageCode = "en-ca"


[params]
  description = "Run by the Institute for the Study of International Development (ISID). The Global Governance Research-to-Practice Lab is bridging the gap between academics, practitioners and policy-makers. It is built around three interconnected nodes: natural resource conflicts and trade-offs, migration and refugees, and governance."
