
# DEVELOPMENT ADDRESS
baseURL = "/"


# PRODUCTION ADDRESS
#baseURL = "https://globalgovernance.lab.mcgill.ca/"


# HUGO SETTINGS
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]
theme = "hugo-gg-lab-v2"


# SITE SETTINGS
title = "Global Governance Lab"
languageCode = "en-ca"
